version: '3.4'

services:
  ordergenerator:
    image: ordergenerator
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4200:4200
